---
title: "ISSS608 G1 Group 5 Project"
site: distill::distill_website
author:
  - name: Chen Yuxi, Jovinka Hartanto, Lim Yong Kai
---

The website documents our Group 5 project to answer [VAST Challenge 2021 Mini Challenge 2](https://vast-challenge.github.io/2021/MC2.html). We prepared an interactive visualisation [*STAGEM*](https://limyongkai.shinyapps.io/ISSS608T5Shiny) using Shiny application to help visualise pattern and identify anomalies and suspicious activities of GASTech employees from the datasets. The application framework is done using R and Shiny, with packages such as ggplot, plotly, tmap, sf, visNetwork and igraph from R.

Our research and development efforts aims to enable users such as Kronos law enforcement with the ability to easily analyse, drill down and identify key suspects and suspicious locations, and thereby speeding up the investigation process. The [background](https://isss608g1group5.netlify.app/about.html) of the case documents the specifics of the challenge.

Our [Practice Research Paper](https://isss608g1group5.netlify.app/researchpaper.html) outlines the motivation, review and critic of past works, design framework, data preparation, the Shiny architecture and analysis techniques used, concluding with our discussion and future works. A detailed [User Guide](https://isss608g1group5.netlify.app/userguide.html) is available to help users get started on our Application. The [Project Poster](https://isss608g1group5.netlify.app/poster.html) provides a quick overview of our work.

The authors are Chen Yuxi, Jovinka Hartanto and Lim Yong Kai with special credits to Professor Kam Tin Seong for his mentorship and guidance in ISSS608 Visual Analytics and Applications course.

The codees for the documents and application is available on our [Github.](https://github.com/jovinkahartanto/Visual-Analytics---Group-Project)