---
title: "Group 5 - Project Proposal"
description: |
  A short description of the post.
author:
  - name: Chen Yuxi, Jovinka Hartanto, Lim Yong Kai
    url: https://example.com/norajones
date: 06-07-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# 1. Overview
In the roughly twenty years that Tethys-based GAStech has been operating a natural gas production site in the island country of Kronos, it has produced remarkable profits and developed strong relationships with the government of Kronos. However, GAStech has not been as successful in demonstrating environmental stewardship.

In January, 2014, the leaders of GAStech are celebrating their new-found fortune as a result of the initial public offering of their very successful company. In the midst of this celebration, several employees of GAStech go missing. An organization known as the Protectors of Kronos (POK) is suspected in the disappearance, but things may not be what they seem.

# 2. Objectives
Both historical vehicle tracking data and transaction data from loyalty and credit card will be used to observe the following issues:

1. The most popular locations and when they are popular
2. Infer the owner of each credit card and loyalty card
3. Identify potential informal or unofficial relationships among GASTech personnel
4. Analyze suspicious activity of the missing personnel prior to the disappearance


# 3. Past Related Work

# 4. Data Sources

# 5. Methodology and Analytical Approach
Our group aims to provide users with an interactive to derive insights from the data source. R packages, such as dplyr, reshape2, and tidyr will be used to perform data manipulation and data transformation. In addition, GGplot2 and Shiny will be used to create visualisations for the app.

The analytical approach of this study are as follow:

1. Exploratory Data Analysis (EDA): to understand the patterns and th relationship between the GPS, car assignment, and transaction data. EDA will also performed to detect any missing data, outliers, and  or anomalies that might exist in the dataset. 
2. Exploratory Spatial Data Analysis (ESDA): to visualize and explore island map and GPS route and to determine the popularity for each location
3. Geospatial and aspatial clustering: to determine unusual relationship between employees and suspicious activities occuring using GPS or transaction data
4. R Markdown and R Shiny to prepare the report and user interface



# 6. Application Design

## Data Visualisation
* Cloropleth maps to identify popular location prior to the disappearance

## Application Interface 
The Shiny App is envisioned to have these functionalities:

* Allow users to input the top n number of popular and suspicious location.
